source "https://rubygems.org"

ruby "3.3.5"

# the core
gem "rails", "~> 8.0.0.rc2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

# Authentication & Authorization
gem "devise", "~> 4.9.4"
gem "pundit", "~> 2.3.1"
gem "rolify", "~> 6.0.1"

# foundation functionality
gem "acts_as_list", "~> 1.1.0"

# frontend stuff
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "view_component"
gem "slim"
gem "slim-rails"
gem "requestjs-rails"

gem "simple_form", "~> 5.3.0"
gem "pagy", "~> 9.1.1"

# api stuff
gem "jbuilder"

# performance and caching
gem "bootsnap", require: false
# gem "redis", ">= 4.0.1"
# gem "kredis"

# media processing
# gem "image_processing", "~> 1.2"

# random stuff
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "ostruct"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end
